name = "byemreh-blog"
main = "src/index.js"
compatibility_date = "2026-08-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "byemreh-blog-db"
database_id = "3a813cc4-4004-4607-96e4-d6a5737cb22f"
